ecom1-master/ecom1-master/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from addresses.views import checkout_address_create_view
from django.conf.urls.static import static
from carts.views import cart_detail_update_view
from payments.views import checkout_payment
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls',namespace='products')),
    path('search/',include('search.urls',namespace='searchs')),
    path('tag/',include('tag.urls',namespace='tags')),
    path('carts/',include('carts.urls',namespace='carts')),
    path('api/cart/',cart_detail_update_view,name="cart_api"),
    path('user/',include('user.urls',namespace='users')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('checkout/address/create/',checkout_address_create_view,name='checkout_address_create'),
    path('accounts/',include('user.password.urls')),
    path('payments/',checkout_payment,name='payments'),


]
if settings.DEBUG:
    urlpatterns=urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom1-master/ecom1-master/products/urls.py
from django.urls import path
from . import views
app_name='products'
urlpatterns=[
       path('',views.ProductListView.as_view(),name='list'),
       path('detail/<slug:slug>/',views.ProductDetailView.as_view(),name='detail'),

]

ecom1-master/ecom1-master/search/urls.py
from django.urls import path
from . import views
app_name='search'
urlpatterns=[
   path('',views.SearchProductListView.as_view(),name='search'),
]

ecom1-master/ecom1-master/tag/urls.py
from django.urls import path

app_name='tag'
urlpatterns=[

]

ecom1-master/ecom1-master/search/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.http import Http404
from products.models import Product
from django.db.models import Q
class SearchProductListView(ListView):
    model=Product
    template_name='search/search_list.html'
    context_object_name='objects'
    def get_queryset(self,*args,**kwargs):
        request=self.request
        query=request.GET.get('q')
        if query:
            lookups=(Q(name__icontains=query)|
            Q(descripation__icontains=query))
            return Product.objects.filter(lookups).distinct()
        else:
            return Product.objects.none()
    def get_context_data(self,*args,**kwargs):
        context=super(SearchProductListView,self).get_context_data(*args,**kwargs)
        context['queryset']=Product.objects.all()
        return context

ecom1-master/ecom1-master/templates/search/search_form.html
<form  method="GET" action="{% url 'searchs:search'%}" class="form my-lg-0">
  <div class="input-group">
      <input class="form-control" type="search" name="q"placeholder="Search" value="{{ request.GET.q }}"aria-label="Search">
      <span class="input-group-btn">
      <button class="btn btn-outline-success" type="submit">Search</button>
      </span>
 </div>
</form>

ecom1-master/ecom1-master/templates/search/search_list.html
{% extends 'base.html'%}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Product | List {% endblock %}
{% block content %}
  {% if request.GET.q %}
  <h1 class="text-center">Result for {{ request.GET.q}}</h1>
  <hr>
  <div class="container">
     <div class="row">
         {% for obj in objects %}
       <div class="col col-4">
         <div class="card shadow-lg p-3 mb-5 bg-white rounded">
           {% if obj.image %}
             <a href="{% url 'products:detail' obj.slug %}"><img src="{{ obj.image.url }}" width="200px" height="200px"class="card-img-top" alt="photo"></a>
           {% endif %}
             <div class="card-body">
               <h5 class="card-title">{{ obj.name }}</h5>
               <p class="card-text">{{ obj.content }}</p>
               <p class="card-title">Rs.{{ obj.price }}</p>
             </div>
          </div>
         </div>
         {% endfor %}
       </div>
   </div>
   {% else %}
   <p> Not found any product.</p>
    {% endif %}
 {% endblock %}