ecom1-master/ecom1-master/carts/urls.py
from django.urls import path
from . import views
app_name='carts'
urlpatterns=[
       path('',views.cart_home,name='cart'),
       path('update/',views.cart_update,name='update'),
       path('checkout/',views.checkout_home,name='checkout'),
]

ecom1-master/ecom1-master/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from addresses.views import checkout_address_create_view
from django.conf.urls.static import static
from carts.views import cart_detail_update_view
from payments.views import checkout_payment
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('products.urls',namespace='products')),
    path('search/',include('search.urls',namespace='searchs')),
    path('tag/',include('tag.urls',namespace='tags')),
    path('carts/',include('carts.urls',namespace='carts')),
    path('api/cart/',cart_detail_update_view,name="cart_api"),
    path('user/',include('user.urls',namespace='users')),
    path('orders/',include('orders.urls',namespace='orders')),
    path('checkout/address/create/',checkout_address_create_view,name='checkout_address_create'),
    path('accounts/',include('user.password.urls')),
    path('payments/',checkout_payment,name='payments'),


]
if settings.DEBUG:
    urlpatterns=urlpatterns+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom1-master/ecom1-master/products/urls.py
from django.urls import path
from . import views
app_name='products'
urlpatterns=[
       path('',views.ProductListView.as_view(),name='list'),
       path('detail/<slug:slug>/',views.ProductDetailView.as_view(),name='detail'),

]

ecom1-master/ecom1-master/tag/urls.py
from django.urls import path

app_name='tag'
urlpatterns=[

]

ecom1-master/ecom1-master/user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url
app_name='user'

urlpatterns=[
     path('account/',views.AccountHomeView.as_view(),name='account_home'),
     path('details/',views.AccountUpdateView.as_view(),name='user-update'),
     path('login/',views.LoginView.as_view(),name='login'),
     path('logout/',views.Logout,name='logout'),
     path('signup/',views.Registration.as_view(),name='signup'),
     url(r'email/activate/confirm/(?P<key>[0-9a-zA-Z]+)/',views.AccountEmailActivationView.as_view(),name='activate_email'),
     path('email/activate/mailsend-your-email-address/',views.email_send,name='email_send'),
]

ecom1-master/ecom1-master/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicons -->
  {% comment %} {% load static %}
 <link href="{% static 'img/favicon.png' %}" rel="icon">
 <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon"> {% endcomment %}

 {% comment %} <!-- Google Fonts -->
 <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800|Montserrat:300,400,700" rel="stylesheet">

 <!-- Bootstrap CSS File -->
 <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">

 <!-- Libraries CSS Files -->
 <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
 <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
 <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
 <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">
 <link href="{% static 'lib/magnific-popup/magnific-popup.css' %}" rel="stylesheet">
 <link href="{% static 'lib/ionicons/css/ionicons.min.css' %}" rel="stylesheet"> {% endcomment %}

 {% comment %} <!-- Main Stylesheet File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet"> {% endcomment %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>{% block style %}{% endblock %}</style>
  </head>
  {% comment %} style="background-color:#D9ECFF; {% endcomment %}
  {% comment %} <body style="background-color:#D9ECFF";> {% endcomment %}
  <body>
    {# navbar #}
    {% include "navbar.html" %}
    {% block content %}
    {% endblock %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

{% comment %}
<script src="{% static 'lib/jquery/jquery.min.js'%}"></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js'%}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'lib/easing/easing.min.js'%}"></script>
  <script src="{% static 'lib/superfish/hoverIntent.js'%}"></script>
  <script src="{% static 'lib/superfish/superfish.min.js'%}"></script>
  <script src="{% static 'lib/wow/wow.min.js'%}"></script>
  <script src="{% static 'lib/owlcarousel/owl.carousel.min.js'%}"></script>
  <script src="{% static 'lib/magnific-popup/magnific-popup.min.js'%}"></script>
  <script src="{% static 'lib/sticky/sticky.js'%}"></script>

  <!-- Contact Form JavaScript File -->
  <script src="{% static 'contactform/contactform.js'%}"></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js'%}"></script> {% endcomment %}
  {% block js %}
  {% endblock %}

<script type="text/javascript">
$(document).ready(function(){
  var productForm=$('.form-product-ajax')
  productForm.submit(function(event){
    event.preventDefault();
    var thisForm=$(this)
    var formData=thisForm.serialize()
    var httpMethod=thisForm.attr('method')
    var endUrl=thisForm.attr('action')
    $.ajax({
      data:formData,
      url:endUrl,
      type:httpMethod,
      success:function(data)
      {
        var submitSpan=thisForm.find(".submit-span")
        if(data.added)
        {
           console.log("count remove",data.cartItemCounts)
           var cartCounts=$('.span-cart-count')
        cartCounts.text(data.cartItemCounts)
           submitSpan.html("<button type='submit' class='btn btn-danger'>Remove Cart</button>")
        }
        else{
          submitSpan.html('<button type="submit" class="btn btn-success">add to cart</button>')
          console.log("count add:",data.cartItemCounts)
          var cartCounts=$('.span-cart-count')
        cartCounts.text(data.cartItemCounts)
        }
        // var cartCounts=$('.span-cart-count')
        // cartCounts.text(data.cartItemCounts)
        var currentPath=window.location.href
        if(currentPath.indexOf('cart')!=-1)
        {
          refreshCart()
        }
      },
      error:function(errorData)
      {
        console.log('error')
      }
    })
  })
     function refreshCart()
     {
        console.log('Hello refresh cart')
        var cartTable=$(".cart-table")
        var cartBody=cartTable.find(".cart-body")
        var productsRow=cartBody.find('.cart-products')
        var currentLocation=window.location.href
        var updateCartUrl='api/cart/';
        var updateMethod="GET";
        var data={};
        $.ajax({
                url:updateCartUrl,
                method:updateMethod,
                data:data,
                success:function(data)
                {
                  console.log('sucess');
                  if(data.proudcts.length>0)
                  {
                    productsRow.html("<tr><td colspan=3>Coming Soon</td></tr>")
                    cartBody.find('.span-subtotal').text(data.subtotal);
                    cartBody.find('.span-total').text(data.total);
                  }
                  else {
                      window.location.href=currentLocation
                  }
                },
                error:function(errorData)
                {
                  console.log('error');
                }
             })
      }
})
</script>
  </body>
</html>

ecom1-master/ecom1-master/templates/messages.html
{% for message in messages %}
  <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}


<!-- {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %} -->

ecom1-master/ecom1-master/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <a class="navbar-brand" href="#"><span style="font-size:35px;font-weight:bold;"><span>FastDealIndia</span></a>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">About Us</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'products:list'%}" tabindex="-1">Products</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'carts:cart' %}" tabindex="-1"><span id="cart_total"class="span-item-count">{{ request.session.cart_items }}</span>Cart</a>
      </li>
      <li class="nav-item">
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ request.user.fullname }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{% url 'users:user-update'%}">Profile</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Order</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
            </div>
        {% else %}
        <a class="nav-link" href="{% url 'users:login'%}" tabindex="-1">Login</a>
        {% endif %}
        </li>
    </ul>
  {% include 'search/search_form.html'%}
  </div>
</nav>